### ISSUE TITLE
Add JavaDocs to the code + refactor Abstract Agents

### ISSUE THREAD

**Issue by soffi49** [Extended-Green-Cloud/green-cloud#18]
**Goal**
Add JavaDocs to all public functions in the existing code

**Task list**
- [x] Add JavaDocs to all Agents and Abstract Agents
- [x] Add JavaDosc to all Behaviours
- [x] Move all messages to common
- [x] Refactor Abstract Agents to include only the necessary fields
