### ISSUE TITLE
Implement future jobs in the application

### ISSUE THREAD

**Issue by soffi49** [Extended-Green-Cloud/green-cloud#19]
**Goal**
The client should be able to schedule jobs for the future

**Task list**
- [x] Add the type of jobs (as Enum) to distinguish _FEATURE_, _INPROGRESS_, _PROCESSING_ jobs
- [x] Add Waker Behaviour which will start job execution at the given time
- [x] Implement the job retrieval mechanism
- [x] Write scenarios presenting the implemented functionality
