### ISSUE TITLE
Add the Weather Library for Monitoring Agent + add power calculation algorithm

### ISSUE THREAD

**Issue by soffi49** [Extended-Green-Cloud/green-cloud#20]
**Goal**
Integrate the Monitoring Agent with the existing weather library, which will retrieve the real weather for a given specific location.
Implement the algorithm that, based on the given weather, will calculate the available power.

**Task list**
- [x] Add the Weather Library to the project
- [x] Integrate the Weather Library with the Monitoring Agent
- [x] Add cache for weather
- [x] Prepare the power calculation algorithm which will calculate power based on weather
- [x] Modify agents behaviour to be aware of weather changes - in timespan
- [x] Run test scenarios testing the Weather Library
- [x] Implement the power calculation algorithm into existing behavior
- [x] Run test scenarios testing the Weather Library
