### ISSUE TITLE
Implement Behaviour handling the dynamic changes in weather

### ISSUE THREAD

**Issue by soffi49** [Extended-Green-Cloud/green-cloud#21]
**Goal**
Implement Behaviour which will respond to the unexpected changes of the weather

**Task List**
- [x] Implement Behaviour which will send the weather updates to the Green Source
- [x] Implement Behaviour which will handle the unexpected weather changes
- [x] Write scenarios and test the implemented functionalities
