### ISSUE TITLE
Implement Behaviour handling unexpected network fluctuations

### ISSUE THREAD

**Issue by soffi49** [Extended-Green-Cloud/green-cloud#23]
**Goal**
Implement behaviour that will handle unexpected network fluctuations and redistribute the work between remaining available servers

**Task List**
- [x] Prepare an algorithm which will handle the unexpected network fluctuations and redistribute the work between working servers
- [x] Implement the algorithm
- [x] Write the test scenarios and run them
