### ISSUE TITLE
Implement Client cancelling the given job

### ISSUE THREAD

**Issue by soffi49** [Extended-Green-Cloud/green-cloud#24]
**Goal**
Implement behavior handling the case when the Client cancels the given job

**Task List**
- [ ] Prepare the algorithm which will handle the client's job cancelation
- [ ] Implement the algorithm (take into account the available power, and scheduled jobs)
- [ ] Write tests scenarios and run them
