### ISSUE TITLE
Implement the GUI 

### ISSUE THREAD

**Issue by soffi49** [Extended-Green-Cloud/green-cloud#25]
**Goal**
Implement the GUI which will present how the network works and how the jobs are flowing in it.

**Task List**
- [ ] Add the GUI framework
- [ ] Implement the agents statically so that they are displayed in the network
- [ ] Implement the visualization of the job flow
- [ ] Add the panel displaying which jobs are currently in progress in the network
- [ ] Implement a panel displaying details regarding jobs
- [ ] Implement panel displaying details regarding servers
