### ISSUE TITLE
Add tests to the application

### ISSUE THREAD

**Issue by soffi49** [Extended-Green-Cloud/green-cloud#26]
**Goal**
Add better test scenarios than XML (to run more complicated tests, for example, to test how the network works for a thousand agents)

**Task List**
- [ ] Implement testing library
- [ ] Write Tests for simple scenarios
- [ ] Write Tests for complicated scenarios
- [ ] Make the tests "green"
