### ISSUE TITLE
Optimize the application

### ISSUE THREAD

**Issue by soffi49** [Extended-Green-Cloud/green-cloud#27]
**Goal**
Add some optimization algorithms which will make the redistribution of power more balanced

**Task List**
- [ ] Prepare some optimization algorithms for balancing the power and jobs distribution
- [ ] Prepare some optimization algorithms which will make the communication run faster
- [ ] Implement the prepared algorithms and test them
