### ISSUE TITLE
Write the documentation

### ISSUE THREAD

**Issue by soffi49** [Extended-Green-Cloud/green-cloud#28]
**Goal**
Prepare the written documentation in LATEX

**Task List**
- [ ] Prepare the abstract
- [ ] Prepare the introduction describing the subject of the project
- [ ] Prepare the description of test scenarios and the considered system functionalities
- [ ] Describe the system structure and the communication exchange schemes
- [ ] Described the GUI and what are its capabilities
- [ ] Described the run test scenarios
- [ ] Describe the possible enhancements that can be added to the system in the future
- [ ] Prepare the bibliography
